name: Build and Deploy

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        
    - name: Install dependencies
      run: npm install

    - name: Build web application
      run: npm run build
      env:
        CI: false
      
    - name: Deploy Web App to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        
    - name: Upload Web Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CityFind-Web-Build
        path: build/
        
    - name: Setup Java for Android APK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Add Capacitor to project
      run: |
        npm install @capacitor/cli @capacitor/core
        npm install @capacitor/android
        npx cap init CityFind com.jayrajsinh45.cityfind --web-dir build
        npx cap add android
        npx cap sync android
        
    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew
      
    - name: Build Android APK
      run: |
        cd android
        echo "configurations.all { resolutionStrategy { force 'org.bouncycastle:bcprov-jdk15to18:1.78.1'; force 'org.bouncycastle:bcprov-jdk18on:1.78.1' } }" >> app/build.gradle
        ./gradlew assembleDebug --no-daemon --no-parallel --stacktrace
        
    - name: Upload Android APK
      uses: actions/upload-artifact@v4
      with:
        name: CityFind-Android-APK
        path: android/app/build/outputs/apk/debug/app-debug.apk
